[package]
name = "mqtt-v5"
description = "Rust types, encode/decode functions, and a tokio codec for MQTT V5"
license = "MIT"
readme = "README.md"
repository = "https://github.com/bschwind/mqtt-broker"
version = "0.1.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
edition = "2018"

[features]
default = ["codec"]
codec = ["tokio-util"]

[dependencies]
bytes = "0.5.0"
tokio-util = { optional = true, version = "0.2", features = ["codec"] }
num_enum = "0.4"
